version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: 'mysql_cont'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Productmanagement
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

  django_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'django_cont'
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    depends_on:
      db:
        condition: service_healthy
    command: ["sh", "-c", "sleep 120 && python manage.py makemigrations && python manage.py migrate && gunicorn PMS.wsgi:application --bind 0.0.0.0:8000"]

  nginx:
    build:
      context: ./nginx
    image: nginx
    container_name: 'nginx_cont'
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - django_app

volumes:
  static_volume:
